services:
  - type: web
    name: qsar-backend
    runtime: image          # Use Docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0       