services:
  - type: web
    name: qsar-backend
    runtime: image # Changed from 'python' to 'image'
    plan: free
    # Remove the buildCommand and startCommand
    # Dockerfile will handle build and start
    dockerfilePath: ./Dockerfile # Points to your Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 # This will be used by the Docker image  